import { LinuxDE, DisplayServer, DetectedOS } from "./osDetect";

export interface ScriptParams {
  wallpaperUrl:  string;
  wallpaperId:   string;
  os:            DetectedOS;
  linuxDE?:      LinuxDE;
  displayServer?: DisplayServer;
}

// ─── Shared download snippet ────────────────────────────────────────────────

const LINUX_DOWNLOAD = (wallDir: string, wallFile: string, wallpaperUrl: string) => `
# ── 1. Create target directory ───────────────────────────────────────────────
mkdir -p "${wallDir}"

# ── 2. Download wallpaper ────────────────────────────────────────────────────
if command -v wget &>/dev/null; then
  wget -q --show-progress -O "${wallFile}" "${wallpaperUrl}"
elif command -v curl &>/dev/null; then
  curl -L --progress-bar -o "${wallFile}" "${wallpaperUrl}"
else
  echo "❌ Neither wget nor curl found. Please install one of them." >&2
  exit 1
fi
echo "✅ Downloaded → ${wallFile}"`.trimStart();

// ─── Script generators ──────────────────────────────────────────────────────

function scriptGNOME(wallFile: string, wallpaperUrl: string, wallDir: string, ds: DisplayServer): string {
  const uriPrefix = ds === "wayland" ? "file://" : "file://";
  return `#!/usr/bin/env bash
# Wolly Auto-Apply — GNOME (${ds === "wayland" ? "Wayland" : "X11"})
# Generated by Wolly Desktop Applier

set -euo pipefail

WALLPAPER_URL="${wallpaperUrl}"
WALLPAPER_DIR="${wallDir}"
WALLPAPER_FILE="${wallFile}"

${LINUX_DOWNLOAD(wallDir, wallFile, wallpaperUrl)}

# ── 3. Apply wallpaper ───────────────────────────────────────────────────────
URI="${uriPrefix}${wallFile}"

echo "🖼  Setting desktop wallpaper..."
gsettings set org.gnome.desktop.background picture-uri       "$URI"
gsettings set org.gnome.desktop.background picture-uri-dark  "$URI"
gsettings set org.gnome.desktop.background picture-options   "zoom"

echo "🔒 Setting lock screen wallpaper..."
gsettings set org.gnome.desktop.screensaver picture-uri      "$URI"
gsettings set org.gnome.desktop.screensaver picture-options  "zoom"

echo ""
echo "✅ Done! Wallpaper applied to desktop and lock screen."
`;
}

function scriptKDE6(wallFile: string, wallpaperUrl: string, wallDir: string): string {
  return `#!/usr/bin/env bash
# Wolly Auto-Apply — KDE Plasma 6 (Wayland & X11)
# Uses plasma-apply-wallpaperimage (Plasma 6+)
# Generated by Wolly Desktop Applier

set -euo pipefail

WALLPAPER_URL="${wallpaperUrl}"
WALLPAPER_DIR="${wallDir}"
WALLPAPER_FILE="${wallFile}"

${LINUX_DOWNLOAD(wallDir, wallFile, wallpaperUrl)}

# ── 3. Apply to desktop ──────────────────────────────────────────────────────
echo "🖼  Setting desktop wallpaper (all screens)..."
plasma-apply-wallpaperimage "$WALLPAPER_FILE"

# ── 4. Apply to lock screen ──────────────────────────────────────────────────
echo "🔒 Setting lock screen wallpaper..."
plasma-apply-wallpaperimage --lockscreen "$WALLPAPER_FILE"

echo ""
echo "✅ Done! Wallpaper applied to desktop and lock screen."
`;
}

function scriptKDE5(wallFile: string, wallpaperUrl: string, wallDir: string): string {
  return `#!/usr/bin/env bash
# Wolly Auto-Apply — KDE Plasma 5 (Wayland & X11)
# Uses qdbus / kwriteconfig5
# Generated by Wolly Desktop Applier

set -euo pipefail

WALLPAPER_URL="${wallpaperUrl}"
WALLPAPER_DIR="${wallDir}"
WALLPAPER_FILE="${wallFile}"

${LINUX_DOWNLOAD(wallDir, wallFile, wallpaperUrl)}

# ── 3. Apply to all desktops via qdbus ──────────────────────────────────────
echo "🖼  Setting desktop wallpaper via qdbus..."
qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "
  var allDesktops = desktops();
  for (var i = 0; i < allDesktops.length; i++) {
    var d = allDesktops[i];
    d.wallpaperPlugin = 'org.kde.image';
    d.currentConfigGroup = ['Wallpaper', 'org.kde.image', 'General'];
    d.writeConfig('Image', 'file://$WALLPAPER_FILE');
    d.writeConfig('FillMode', 6);
  }
"

# ── 4. Apply to lock screen via kwriteconfig5 ────────────────────────────────
echo "🔒 Setting lock screen wallpaper via kwriteconfig5..."
kwriteconfig5 \\
  --file kscreenlockerrc \\
  --group  "Greeter"                       \\
  --group  "Wallpaper"                     \\
  --group  "org.kde.image"                 \\
  --group  "General"                       \\
  --key    "Image"   "file://$WALLPAPER_FILE"

# Reload kscreenlocker config
kquitapp5 kscreenlocker_greet 2>/dev/null || true

echo ""
echo "✅ Done! Wallpaper applied to desktop and lock screen."
`;
}

function scriptHyprland(wallFile: string, wallpaperUrl: string, wallDir: string): string {
  return `#!/usr/bin/env bash
# Wolly Auto-Apply — Hyprland (Wayland)
# Uses swww (preferred) with hyprpaper fallback
# Generated by Wolly Desktop Applier

set -euo pipefail

WALLPAPER_URL="${wallpaperUrl}"
WALLPAPER_DIR="${wallDir}"
WALLPAPER_FILE="${wallFile}"

${LINUX_DOWNLOAD(wallDir, wallFile, wallpaperUrl)}

# ── 3. Apply wallpaper ───────────────────────────────────────────────────────
if command -v swww &>/dev/null; then
  echo "🖼  Using swww..."
  # Initialise daemon if not running
  swww query &>/dev/null || swww init
  swww img "$WALLPAPER_FILE" \\
    --transition-type     wipe \\
    --transition-angle    45   \\
    --transition-duration 1.5
  echo "✅ Done! swww wallpaper applied."

elif command -v hyprpaper &>/dev/null; then
  echo "🖼  Using hyprpaper..."
  CONF="$HOME/.config/hypr/hyprpaper.conf"
  # Persist setting
  echo "preload  = $WALLPAPER_FILE"  > "$CONF"
  echo "wallpaper = ,$WALLPAPER_FILE" >> "$CONF"
  pkill hyprpaper 2>/dev/null; sleep 0.2
  hyprpaper &
  echo "✅ Done! hyprpaper wallpaper applied."

else
  echo "⚠  Neither swww nor hyprpaper found."
  echo "   Install swww:     yay -S swww"
  echo "   Install hyprpaper: yay -S hyprpaper"
fi
`;
}

function scriptSway(wallFile: string, wallpaperUrl: string, wallDir: string): string {
  return `#!/usr/bin/env bash
# Wolly Auto-Apply — Sway (Wayland)
# Uses swaybg
# Generated by Wolly Desktop Applier

set -euo pipefail

WALLPAPER_URL="${wallpaperUrl}"
WALLPAPER_DIR="${wallDir}"
WALLPAPER_FILE="${wallFile}"

${LINUX_DOWNLOAD(wallDir, wallFile, wallpaperUrl)}

# ── 3. Apply via swaybg ──────────────────────────────────────────────────────
echo "🖼  Setting wallpaper via swaybg..."

if command -v swaybg &>/dev/null; then
  # Kill previous swaybg instance
  pkill swaybg 2>/dev/null || true
  swaybg -m fill -i "$WALLPAPER_FILE" &
  echo "✅ Done! swaybg running in background."

  echo ""
  echo "💡 To make this permanent, add to ~/.config/sway/config:"
  echo "   output * bg $WALLPAPER_FILE fill"
else
  echo "❌ swaybg not found. Install it:"
  echo "   pacman -S swaybg   # Arch"
  echo "   apt install swaybg # Debian/Ubuntu"
fi
`;
}

function scriptXFCE(wallFile: string, wallpaperUrl: string, wallDir: string): string {
  return `#!/usr/bin/env bash
# Wolly Auto-Apply — XFCE / feh
# Generated by Wolly Desktop Applier

set -euo pipefail

WALLPAPER_URL="${wallpaperUrl}"
WALLPAPER_DIR="${wallDir}"
WALLPAPER_FILE="${wallFile}"

${LINUX_DOWNLOAD(wallDir, wallFile, wallpaperUrl)}

# ── 3. Apply wallpaper ───────────────────────────────────────────────────────
if command -v xfconf-query &>/dev/null; then
  echo "🖼  Setting XFCE wallpaper..."
  # Get all XFCE desktop monitors
  MONITORS=$(xfconf-query -c xfce4-desktop -l 2>/dev/null | grep last-image | sed 's|/last-image||')
  for MONITOR in $MONITORS; do
    xfconf-query -c xfce4-desktop -p "$MONITOR/last-image"   -s "$WALLPAPER_FILE"
    xfconf-query -c xfce4-desktop -p "$MONITOR/image-style"  -s 5
    xfconf-query -c xfce4-desktop -p "$MONITOR/image-show"   -s true
  done
  xfdesktop --reload 2>/dev/null || true
  echo "✅ Done! XFCE wallpaper applied."

elif command -v feh &>/dev/null; then
  echo "🖼  Setting wallpaper via feh..."
  feh --bg-fill "$WALLPAPER_FILE"
  # Persist across restarts
  echo "feh --bg-fill '$WALLPAPER_FILE'" > "$HOME/.fehbg"
  chmod +x "$HOME/.fehbg"
  echo "✅ Done! feh wallpaper applied (add ~/.fehbg to your autostart)."

else
  echo "❌ Neither xfconf-query nor feh found."
  echo "   Install feh:  pacman -S feh   # Arch"
  echo "                 apt install feh # Debian/Ubuntu"
fi
`;
}

function scriptMacOS(wallFile: string, wallpaperUrl: string, wallDir: string): string {
  const macDir = wallDir.replace("$HOME", "$HOME");
  return `#!/usr/bin/env bash
# Wolly Auto-Apply — macOS
# Generated by Wolly Desktop Applier

set -euo pipefail

WALLPAPER_URL="${wallpaperUrl}"
WALLPAPER_DIR="${macDir}"
WALLPAPER_FILE="${wallFile}"

# ── 1. Create target directory ───────────────────────────────────────────────
mkdir -p "$WALLPAPER_DIR"

# ── 2. Download wallpaper ────────────────────────────────────────────────────
echo "⬇  Downloading wallpaper..."
curl -L --progress-bar -o "$WALLPAPER_FILE" "$WALLPAPER_URL"
echo "✅ Downloaded → $WALLPAPER_FILE"

# ── 3. Apply wallpaper ───────────────────────────────────────────────────────
echo "🖼  Setting desktop wallpaper..."
osascript -e "
  tell application \"System Events\"
    tell every desktop
      set picture to POSIX file \"$WALLPAPER_FILE\"
    end tell
  end tell
"

echo ""
echo "✅ Done! Wallpaper applied."
`;
}

function scriptWindows(wallFile: string, wallpaperUrl: string, wallDir: string): string {
  const winDir  = wallDir.replace("$HOME", "$env:USERPROFILE");
  const winFile = wallFile.replace("$HOME", "$env:USERPROFILE");
  return `# Wolly Auto-Apply — Windows (PowerShell)
# Run as: powershell -ExecutionPolicy Bypass -File wolly-apply.ps1
# Generated by Wolly Desktop Applier

$WallpaperUrl  = "${wallpaperUrl}"
$WallpaperDir  = "${winDir}"
$WallpaperFile = "${winFile}"

# ── 1. Create target directory ────────────────────────────────────────────────
New-Item -ItemType Directory -Force -Path $WallpaperDir | Out-Null

# ── 2. Download wallpaper ─────────────────────────────────────────────────────
Write-Host "⬇  Downloading wallpaper..."
Invoke-WebRequest -Uri $WallpaperUrl -OutFile $WallpaperFile
Write-Host "✅ Downloaded → $WallpaperFile"

# ── 3. Apply wallpaper via Win32 API ──────────────────────────────────────────
Write-Host "🖼  Setting desktop wallpaper..."
Add-Type -TypeDefinition @"
using System;
using System.Runtime.InteropServices;
public class Wallpaper {
  [DllImport("user32.dll", CharSet = CharSet.Auto)]
  public static extern int SystemParametersInfo(
    int uAction, int uParam, string lpvParam, int fuWinIni);
}
"@
[Wallpaper]::SystemParametersInfo(20, 0, $WallpaperFile, 3) | Out-Null

Write-Host ""
Write-Host "✅ Done! Wallpaper applied."
`;
}

// ─── Public API ────────────────────────────────────────────────────────────

export interface GeneratedScript {
  code:     string;
  lang:     "bash" | "powershell";
  filename: string;
  wallDir:  string;
  wallFile: string;
}

export function generateScript(p: ScriptParams): GeneratedScript {
  const fileName = `wolly-${p.wallpaperId}.jpg`;
  const wallDir  =
    p.os === "windows"
      ? "$env:USERPROFILE\\Pictures\\wall"
      : "$HOME/Pictures/wall";
  const wallFile =
    p.os === "windows"
      ? `${wallDir}\\${fileName}`
      : `${wallDir}/${fileName}`;

  let code = "";
  let lang: "bash" | "powershell" = "bash";
  let scriptName = "wolly-apply.sh";

  if (p.os === "windows") {
    code       = scriptWindows(wallFile, p.wallpaperUrl, wallDir);
    lang       = "powershell";
    scriptName = "wolly-apply.ps1";
  } else if (p.os === "macos") {
    code       = scriptMacOS(wallFile, p.wallpaperUrl, wallDir);
    scriptName = "wolly-apply.sh";
  } else {
    // Linux — pick by DE
    switch (p.linuxDE) {
      case "gnome":    code = scriptGNOME(wallFile, p.wallpaperUrl, wallDir, p.displayServer ?? "wayland"); break;
      case "kde6":     code = scriptKDE6(wallFile, p.wallpaperUrl, wallDir);     break;
      case "kde5":     code = scriptKDE5(wallFile, p.wallpaperUrl, wallDir);     break;
      case "hyprland": code = scriptHyprland(wallFile, p.wallpaperUrl, wallDir); break;
      case "sway":     code = scriptSway(wallFile, p.wallpaperUrl, wallDir);     break;
      default:         code = scriptXFCE(wallFile, p.wallpaperUrl, wallDir);     break;
    }
    scriptName = "wolly-apply.sh";
  }

  return { code, lang, filename: scriptName, wallDir, wallFile };
}

export function downloadScript(script: GeneratedScript): void {
  const mime = script.lang === "powershell" ? "text/plain" : "text/x-sh";
  const blob = new Blob([script.code], { type: mime });
  const link = document.createElement("a");
  link.href     = URL.createObjectURL(blob);
  link.download = script.filename;
  link.click();
}